export const contactsInfoSeeder = [
  expect(response.body).toHaveProperty("email");,
  {
    id: 'Colombia_Hotel_2',
    name: 'Sofitel Legend Santa Clara',
    email: 'info@hotelessofitel.com',
    phone: '+57 605 6543202',
    hotelId: 'Colombia_Hotel_2',
  },
  {
    id: 'Colombia_Hotel_3',
    name: 'JW Marriott Hotel',
    email: 'info@hotelesmarriott.com',
    phone: '+57 605 6543203',
    hotelId: 'Colombia_Hotel_3',
  },
  {
    id: 'Colombia_Hotel_4',
    name: 'Hotel Las Islas',
    email: 'info@hoteleslasislas.com',
    phone: '+57 605 6543204',
    hotelId: 'Colombia_Hotel_4',
  },
  {
    id: 'Colombia_Hotel_5',
    name: 'Hotel Casa San Agustín',
    email: 'info@hotelessanagustin.com',
    phone: '+57 605 6543205',
    hotelId: 'Colombia_Hotel_5',
  },
  {
    id: 'Colombia_Hotel_6',
    name: 'Hotel Four Seasons Casa Medina',
    email: 'info@hotelesfourseasongs.com',
    phone: '+57 605 6543206',
    hotelId: 'Colombia_Hotel_6',
  },
  {
    id: 'Colombia_Hotel_7',
    name: 'Hotel Boutique Casa Pestagua',
    email: 'info@hotelescasapestagua.com',
    phone: '+57 605 6543207',
    hotelId: 'Colombia_Hotel_7',
  },
  {
    id: 'Colombia_Hotel_8',
    name: 'Hotel Estelar Milla de Oro',
    email: 'info@hotelesmilladeoro.com',
    phone: '+57 605 6543208',
    hotelId: 'Colombia_Hotel_8',
  },
  {
    id: 'Colombia_Hotel_9',
    name: 'Hotel Sofitel Bogotá Victoria Regia',
    email: 'info@hotelesvictoriaregia.com',
    phone: '+57 605 6543209',
    hotelId: 'Colombia_Hotel_9',
  },
  {
    id: 'Colombia_Hotel_10',
    name: 'Hotel InterContinental Cartagena de Indias',
    email: 'info@hotelescartagenadeindias.com',
    phone: '+57 605 6543210',
    hotelId: 'Colombia_Hotel_10',
  },
  {
    id: 'Colombia_Hotel_11',
    name: 'Hotel Dann Carlton',
    email: 'info@hotelesdanncarlton.com',
    phone: '+57 605 6543211',
    hotelId: 'Colombia_Hotel_11',
  },
  {
    id: 'Colombia_Hotel_12',
    name: 'Hotel NH Collection Bogotá Teleport Royal',
    email: 'info@hotelesteleportroyal.com',
    phone: '+57 605 6543212',
    hotelId: 'Colombia_Hotel_12',
  },
  {
    id: 'Colombia_Hotel_13',
    name: 'Hotel Movich Cartagena de Indias',
    email: 'info@hotelesmovich.com',
    phone: '+57 605 6543213',
    hotelId: 'Colombia_Hotel_13',
  },
  {
    id: 'Colombia_Hotel_14',
    name: 'Hotel Click Clack',
    email: 'info@hotelesclickclack.com',
    phone: '+57 605 6543214',
    hotelId: 'Colombia_Hotel_14',
  },
  {
    id: 'Colombia_Hotel_15',
    name: 'Hotel Boutique Bovedas de Santa Clara',
    email: 'info@hotelessantaclara.com',
    phone: '+57 605 6543215',
    hotelId: 'Colombia_Hotel_15',
  },
  {
    id: 'Colombia_Hotel_16',
    name: 'Hotel W',
    email: 'info@hotelesw.com',
    phone: '+57 605 6543216',
    hotelId: 'Colombia_Hotel_16',
  },
  {
    id: 'Colombia_Hotel_17',
    name: 'Hotel Estelar Grand Playa Manzanillo',
    email: 'info@hotelesmanzanillo.com',
    phone: '+57 605 6543217',
    hotelId: 'Colombia_Hotel_17',
  },
  {
    id: 'Colombia_Hotel_18',
    name: 'Hotel NH Collection Royal Smartsuites',
    email: 'info@hotelessmartsuites.com',
    phone: '+57 605 6543206',
    hotelId: 'Colombia_Hotel_18',
  },
  {
    id: 'Colombia_Hotel_19',
    name: 'Hotel NH Bogotá',
    email: 'info@hotelesnhbogota.com',
    phone: '+57 605 6543219',
    hotelId: 'Colombia_Hotel_19',
  },
  {
    id: 'Colombia_Hotel_20',
    name: 'Hotel Santa Marta Beach',
    email: 'info@hotelesmartabeach.com',
    phone: '+57 605 6543220',
    hotelId: 'Colombia_Hotel_20',
  },
  {
    id: 'Colombia_Hotel_21',
    name: 'Hotel Los Andes',
    email: 'info@hoteleslosandes.com',
    phone: '+57 605 6543221',
    hotelId: 'Colombia_Hotel_21',
  },
  {
    id: 'Colombia_Hotel_22',
    name: 'Hotel Villa de Leyva Retreat',
    email: 'info@hotelesleyvaretreat.com',
    phone: '+57 605 6543222',
    hotelId: 'Colombia_Hotel_22',
  },
  {
    id: 'Colombia_Hotel_23',
    name: 'Hotel Hilton Bogotá',
    email: 'info@hoteleshiltonbogota.com',
    phone: '+57 605 6543223',
    hotelId: 'Colombia_Hotel_23',
  },
  {
    id: 'Colombia_Hotel_24',
    name: 'Hotel Las Américas Resort',
    email: 'info@hotelesamericasresort.com',
    phone: '+57 605 6543224',
    hotelId: 'Colombia_Hotel_24',
  },
  {
    id: 'Colombia_Hotel_25',
    name: 'Hotel Cosmos 100',
    email: 'info@hotelescosmos100.com',
    phone: '+57 605 6543225',
    hotelId: 'Colombia_Hotel_25',
  },
  {
    id: 'Colombia_Hotel_26',
    name: 'Hotel Estelar Windsor House',
    email: 'info@hoteleswindsorhouse.com',
    phone: '+57 605 6543226',
    hotelId: 'Colombia_Hotel_26',
  },
  {
    id: 'Colombia_Hotel_27',
    name: 'Hotel Capilla del Mar',
    email: 'info@hotelescapilladelmar.com',
    phone: '+57 605 6543227',
    hotelId: 'Colombia_Hotel_27',
  },
  {
    id: 'Colombia_Hotel_28',
    name: 'Hotel Estelar Playa Manzanillo',
    email: 'info@hotelesplayamanzanillo.com',
    phone: '+57 605 6543228',
    hotelId: 'Colombia_Hotel_28',
  },
  {
    id: 'Colombia_Hotel_29',
    name: 'Hotel Estelar Altamira',
    email: 'info@hotelesaltamira.com',
    phone: '+57 605 6543229',
    hotelId: 'Colombia_Hotel_29',
  },
  {
    id: 'Colombia_Hotel_30',
    name: 'Hotel Boutique Quadrifolio',
    email: 'info@hotelesquadrifolio.com',
    phone: '+57 605 6543230',
    hotelId: 'Colombia_Hotel_30',
  },
  {
    id: 'Colombia_Hotel_31',
    name: 'Hotel InterContinental Medellín',
    email: 'info@hotelesmedellin.com',
    phone: '+57 605 6543231',
    hotelId: 'Colombia_Hotel_31',
  },
  {
    id: 'Colombia_Hotel_32',
    name: 'Hotel Dann Carlton Bucaramanga',
    email: 'info@hotelesbucaramanga.com',
    phone: '+57 605 6543232',
    hotelId: 'Colombia_Hotel_32',
  },
{
    id: 'Colombia_Hotel_33',
    name: 'Hotel NH Collection Cali Royal',
    email: 'info@hotelescaliroyal.com',
    phone: '+57 605 6543233',
    hotelId: 'Colombia_Hotel_33',
  },
  {
    id: 'Colombia_Hotel_34',
    name: 'Hotel DoubleTree by Hilton Bogotá Salitre AR',
    email: 'info@hotelessalitrear.com',
    phone: '+57 605 6543234',
    hotelId: 'Colombia_Hotel_34',
  },
  {
    id: 'Colombia_Hotel_35',
    name: 'Hotel Estelar Blue',
    email: 'info@hotelesestelarblue.com',
    phone: '+57 605 6543235',
    hotelId: 'Colombia_Hotel_35',
  },
  {
    id: 'Colombia_Hotel_36',
    name: 'Hotel Estelar En Alto Prado',
    email: 'info@hotelesaltoprado.com',
    phone: '+57 605 6543236',
    hotelId: 'Colombia_Hotel_36',
  },
  {
    id: 'Colombia_Hotel_37',
    name: 'Hotel Dann Cartagena',
    email: 'info@hotelesdanncartagena.com',
    phone: '+57 605 6543237',
    hotelId: 'Colombia_Hotel_37',
  },
{
    id: 'Colombia_Hotel_38',
    name: 'Hotel NH Collection Barranquilla Smartsuites Royal',
    email: 'info@hotelessmartsuites.com',
    phone: '+57 605 6543238',
    hotelId: 'Colombia_Hotel_38',
  },
  {
    id: 'Colombia_Hotel_39',
    name: 'Hotel Hilton Cartagena',
    email: 'info@hoteleshilton.com',
    phone: '+57 605 6543239',
    hotelId: 'Colombia_Hotel_39',
  },
  {
    id: 'Colombia_Hotel_40',
    name: 'Hotel Spiwak Chipichape Cali',
    email: 'info@hoteleseschipichape.com',
    phone: '+57 605 6543240',
    hotelId: 'Colombia_Hotel_40',
  },
  {
    id: 'Colombia_Hotel_41',
    name: 'Hotel Estelar Suites Jones',
    email: 'info@hotelessuitesjones.com',
    phone: '+57 605 6543241',
    hotelId: 'Colombia_Hotel_41',
  },
  {
    id: 'Colombia_Hotel_42',
    name: 'Hotel Estelar La Fontana',
    email: 'info@hoteleslafontana.com',
    phone: '+57 605 6543242',
    hotelId: 'Colombia_Hotel_42',
  },
{
    id: 'Colombia_Hotel_43',
    name: 'Hotel Cosmos 116',
    email: 'info@hotelescosmos116.com',
    phone: '+57 605 6543243',
    hotelId: 'Colombia_Hotel_43',
  },
  {
    id: 'Colombia_Hotel_44',
    name: 'Hotel Charleston Bogotá',
    email: 'info@hotelescharleston.com',
    phone: '+57 605 6543244',
    hotelId: 'Colombia_Hotel_44',
  },
  {
    id: 'Colombia_Hotel_45',
    name: 'Hotel Estelar Windsor House 95',
    email: 'info@hoteleseshouse95.com',
    phone: '+57 605 6543245',
    hotelId: 'Colombia_Hotel_45',
  },
  {
    id: 'Colombia_Hotel_46',
    name: 'Hotel Estelar Miraflores',
    email: 'info@hotelesmiraflores.com',
    phone: '+57 605 6543246',
    hotelId: 'Colombia_Hotel_46',
  },
  {
    id: 'Colombia_Hotel_47',
    name: 'Hotel Cartagena Plaza',
    email: 'info@hotelesbucaramanga.com',
    phone: '+57 605 6543247',
    hotelId: 'Colombia_Hotel_47',
  },
{
    id: 'Colombia_Hotel_48',
    name: 'Hotel Estelar Blue Towers',
    email: 'info@hotelesbluetowers.com',
    phone: '+57 605 6543248',
    hotelId: 'Colombia_Hotel_48',
  },
  {
    id: 'Colombia_Hotel_49',
    name: 'Hotel Estelar Parque De La 93',
    email: 'info@hotelesparquedela93.com',
    phone: '+57 605 6543249',
    hotelId: 'Colombia_Hotel_49',
  },
  {
    id: 'Colombia_Hotel_50',
    name: 'Hotel NH Collection Bogotá Hacienda Royal',
    email: 'info@hoteleseshaciendaroyal.com',
    phone: '+57 605 6543250',
    hotelId: 'Colombia_Hotel_50',
  },
]
